experiment:
    id: 'potsdam_nll'

##Data
data:
    name: 'potsdam'
    # path_to_dataset: 'agri_semantics/datasets/potsdam/'
    # path_to_dataset: 'bayesian_erfnet/agri_semantics/datasets/potsdam/dense_regression'
    path_to_dataset: 'bayesian_erfnet/agri_semantics/datasets/potsdam/semantic_segmentation'
    img_prop:
        width: 400
        height:
        keep_aspect_ratio: true
    depth: 3
    batch_size:
        total: 8
        human: 6
        pseudo: 2
    train_shuffle: true
    num_workers: 0

##Training
train:
    n_gpus: 1
    num_workers: 0
    lr: 0.0001
    max_epoch: 100
    weight_decay: 0.0001
    num_mc_aleatoric: 50
    num_mc_epistemic: 50
    patience: 100
    scheduler: 'one_cycle'  # constant, one_cycle, multi_step
    one_cycle:
        init_lr: 0.00001
        max_lr: 0.05
        final_lr: 0.0001
        anneal_epoch: 20
    multi_step:
        milestones: [150]
        gamma: 0.1

    transformations:
        # random_rotation:
        #   min_angle: -180
        #   max_angle:  180
        #   step_size:   2
        # random_crop:
        #   height:
        #   width: 200
        resize:
          height:
          width: 344
          keep_aspect_ratio: true
        #color_jitter:
        #  brightness: 0.0 # 0.0-1.0
        #  contrast: 0.0 # 0.0-1.0
        #  saturation: 0.8 # 0.0-1.0
        #  hue: 0.0 # -0.5-0.5

val:
    transformations:
        resize:
          height:
          width: 344
          keep_aspect_ratio: true

test:
    transformations:
        resize:
          height:
          width: 344
          keep_aspect_ratio: true

##Network
model:
    name: 'erfnet' # erfnet, bayesian_erfnet, evidential_erfnet
    task: 'classification' # regression, classification
    aleatoric_model: false
    ensemble_model: false
    evidential_model: false
    bilinear_upsampling: false
    num_models: 1
    epistemic_version: 'all'
    deep_encoder: false
    shared_decoder: true
    num_classes: 7
    num_classes_pretrained: 20
    value_range: # used for bounding predicted regression values
        min_value: 0.0
        max_value: 25.5
    loss:
        fn_name: "xentropy" # xentropy, soft_iou, mse, pac_type_2_mle, xentropy_bayes_risk, mse_bayes_risk
        uniform_label_smoothing: 0.00 # [0, 1]
        uncertainty_aware_label_smoothing: false
        kl_div_anneal_epochs: 25
    in_channels: 3
    dropout_prob: 0.5
    # class_frequencies:
    #   - 0.0306
    #   - 0.1668
    #   - 0.5700
    #   - 0.0116
    #   - 0.1768
    #   - 0.0442

##Active Learning
active_learning:
    type: 'all'
    num_collected_images: 50
    max_collected_images: 500
