experiment:
    id: 'active_learning_lawnmower'

##Data
data:
    name: 'potsdam'
    path_to_dataset: 'bayesian_erfnet/agri_semantics/datasets/potsdam/'
    img_prop:
        width: 400
        height:
        keep_aspect_ratio: true
    depth: 3
    batch_size: 8
    train_shuffle: true
    num_workers: 0

##Training
train:
    n_gpus: 1
    num_workers: 4
    max_epoch: 500
    lr: 0.0001
    weight_decay: 0.001
    num_mc_aleatoric: 50
    num_mc_epistemic: 50
    patience: 500

    transformations:
        # random_rotation:
        #   min_angle: -180
        #   max_angle:  180
        #   step_size:   2
        # random_crop:
        #   height:
        #   width: 200
        resize:
          height:
          width: 344
          keep_aspect_ratio: true
        #color_jitter:
        #  brightness: 0.0 # 0.0-1.0
        #  contrast: 0.0 # 0.0-1.0
        #  saturation: 0.8 # 0.0-1.0
        #  hue: 0.0 # -0.5-0.5

val:
    transformations:
        resize:
          height:
          width: 344
          keep_aspect_ratio: true

test:
    transformations:
        resize:
          height:
          width: 344
          keep_aspect_ratio: true

##Network
model:
    name: 'erfnet'
    epistemic_version: 'all'
    deep_encoder: false
    shared_decoder: true
    num_classes: 7
    num_classes_pretrained: 20
    loss: 'xentropy'
    in_channels: 3
    dropout_prob: 0.5
    # class_frequencies:
    #   - 0.0306
    #   - 0.1668
    #   - 0.5700
    #   - 0.0116
    #   - 0.1768
    #   - 0.0442

##Active Learning
active_learning:
    type: 'all'
    num_collected_images: 50
    max_collected_images: 500
