experiment:
    id: 'rit18'

##Data
data:
    name: 'rit18'
    path_to_dataset: 'bayesian_erfnet/agri_semantics/datasets/rit18/semantic_segmentation'
    img_prop:
        width: 400
        height:
        keep_aspect_ratio: true
    depth: 3
    batch_size:
        total: 8
        human: 2
        pseudo: 6
    train_shuffle: true
    num_workers: 4
    merge: true

##Training
train:
    n_gpus: 1
    num_workers: 4
    lr:
        scheduler: true
        init_lr: 0.00001
        max_lr: 0.05
        final_lr: 0.0001
        anneal_epoch: 20
    max_epoch: 100
    weight_decay: 0.0001
    num_mc_aleatoric: 50
    num_mc_epistemic: 50
    patience: 100

    transformations:
        resize:
            height:
            width: 344
            keep_aspect_ratio: true

val:
    transformations:
        resize:
          height:
          width: 344
          keep_aspect_ratio: true

test:
    transformations:
        resize:
          height:
          width: 344
          keep_aspect_ratio: true

##Network
model:
    name: 'erfnet' # erfnet, bayesian_erfnet, evidential_erfnet
    task: 'classification' # regression, classification
    aleatoric_model: false
    ensemble_model: false
    evidential_model: false
    bilinear_upsampling: false
    num_models: 1
    epistemic_version: 'all'
    deep_encoder: false
    shared_decoder: true
    num_classes: 6
    num_classes_pretrained: 6
    value_range: # used for bounding predicted regression values
        min_value: 0.0
        max_value: 25.5
    loss:
        fn_name: "xentropy" # xentropy, soft_iou, mse, pac_type_2_mle, xentropy_bayes_risk, mse_bayes_risk
        uniform_label_smoothing: 0.00 # [0, 1]
        uncertainty_aware_label_smoothing: false
        kl_div_anneal_epochs: 25
    in_channels: 3
    dropout_prob: 0.5

# Active Learning
active_learning:
    type: 'all'
    num_collected_images: 100
    max_collected_images: 1000
